steps:
  - label: "Simple Unit Test"
    depends_on: upload-ready-pipeline
    agents:
      queue: "ascend-a2b3"
      resource_class: "npu-1"
    image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
            - name: swr-secret
    env:
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      VLLM_USE_MODELSCOPE: "True"
    commands:
      - export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH
      - "timeout 60m pytest -v -s -m 'core_model and cpu' --cov=vllm_omni --cov-branch --cov-report=term-missing --cov-report=html --cov-report=xml"

  - label: "Diffusion Model Test"
    depends_on: upload-ready-pipeline
    agents:
      queue: "ascend-a2b3"
      resource_class: "npu-1"
    image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
            - name: swr-secret
    env:
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      VLLM_USE_MODELSCOPE: "True"
    commands:
      - export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH
      - timeout 30m pytest -s -v tests/e2e/offline_inference/test_t2i_model.py -m "core_model and diffusion" --run-level "core_model"

  - label: "Diffusion Model CPU offloading Test"
    depends_on: upload-ready-pipeline
    agents:
      queue: "ascend-a2b3"
      resource_class: "npu-1"
    image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
            - name: swr-secret
    env:
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      VLLM_USE_MODELSCOPE: "True"
    commands:
      - export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH
      - timeout 10m pytest -s -v tests/e2e/offline_inference/test_diffusion_cpu_offload.py

  - label: "Diffusion Sequence Parallelism Test"
    depends_on: upload-ready-pipeline
    agents:
      queue: "ascend-a2b3"
      resource_class: "npu-1"
    image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
            - name: swr-secret
    env:
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      VLLM_USE_MODELSCOPE: "True"
    commands:
      - export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH
      - timeout 20m pytest -s -v tests/e2e/offline_inference/test_sequence_parallel.py -m core_model

  - label: "Qwen3-TTS E2E Test"
    depends_on: upload-ready-pipeline-a3
    agents:
      queue: "ascend-a3"
      resource_class: "npu-2"
    image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
            - name: swr-secret
    env:
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      VLLM_USE_MODELSCOPE: "True"
    commands:
      - |
        timeout 20m bash -c '
          export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH
          export VLLM_LOGGING_LEVEL=DEBUG
          export VLLM_ALLOW_LONG_MAX_MODEL_LEN="1"
          pytest -s -v tests/e2e/online_serving/test_qwen3_tts_customvoice.py -m "core_model" --run-level "core_model"
        '
