ARG VLLM_ASCEND_IMAGE=quay.nju.edu.cn/ascend/vllm-ascend
ARG VLLM_ASCEND_TAG=v0.14.0rc1
FROM ${VLLM_ASCEND_IMAGE}:${VLLM_ASCEND_TAG}

ARG APP_DIR=/vllm-workspace/vllm-omni
WORKDIR ${APP_DIR}

COPY . .

# Remove this replace when the dispatch of requirements is ready
RUN sed -i 's/^fa3-fwd==0.0.1/# fa3-fwd==0.0.1/' pyproject.toml \
 && sed -i 's/\bonnxruntime\b/onnxruntime-cann/' pyproject.toml

# Install vllm-omni with dev dependencies
RUN pip install --no-cache-dir -e ".[dev]"

ENV VLLM_WORKER_MULTIPROC_METHOD=spawn

ENTRYPOINT []
