ARG VLLM_ASCEND_IMAGE=quay.nju.edu.cn/ascend/vllm-ascend
ARG VLLM_ASCEND_TAG=v0.12.0rc1-a3
FROM ${VLLM_ASCEND_IMAGE}:${VLLM_ASCEND_TAG}

ARG APP_DIR=/vllm-workspace/vllm-omni
WORKDIR ${APP_DIR}

COPY . .

# Install the missing Mooncake dependencies in vllm-ascend v0.12.0rc1 image
# Removed in next version
RUN apt-get update -y && \
    apt-get install -y libjemalloc2
RUN echo "export LD_PRELOAD=/usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2:$LD_PRELOAD" >> ~/.bashrc

# Install vllm-omni with dev dependencies
RUN pip install --no-cache-dir -e ".[dev]"

ENV VLLM_WORKER_MULTIPROC_METHOD=spawn

ENTRYPOINT []
